
name: Android Build
on:
  push:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # - name: gradlew
      #   run: gradle
      # - name: Build with Gradle
      #   run: gradle build

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: gradle assembleRelease
